Homework1
made-ml-in-prod-2021/ningeen pull request #4
Opened 2021-05-22 17:38 UTC by ningeen

Основные архитектурные решения:
1. Для конфигов используется hydra
2. Для тестов генерируются синтетические данные с использованием faker
3. В качестве кастомного трансформера написан класс RankTransformer для преобразования фичи в ранговое представление
4. В качестве артефактов для функции predict необходимо подать датасет, модель и трансформер.
5. Во время EDA генерируется отчет через pandas profiling, не ручной скрипт для отчета, но я бы пол балла засчитал.
6. Для запуска predict нужно указать папку с артефактами тренироваки в папке outputs:
`python src/predict_pipeline.py artifacts_dir={outputs_folder}`

P.S. Выполнены все пункты ДЗ, кроме CI, поэтому оцениваю свою работу в 34.5 балла.

---

:heavy_plus_sign: -2) Назовите ветку homework1 (1 балл)

:heavy_plus_sign: -1) положите код в папку ml_project

:heavy_plus_sign: 0) В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла)

:heavy_plus_sign: 1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов)
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)

:heavy_plus_sign: 2) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов)  

:heavy_plus_sign: 3) использованы логгеры (2 балла)

:heavy_plus_sign: 4) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов)

:heavy_plus_sign: 5) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов)
- можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
- можно просто руками посоздавать данных, собственноручно написанными функциями
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается)

:heavy_plus_sign: 6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) 

:heavy_plus_sign: 7) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла) 

:heavy_plus_sign: 8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла)

:heavy_plus_sign: 9) Обучите модель, запишите в readme как это предлагается (3 балла)

:heavy_plus_sign: 10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла)  

:heavy_plus_sign: 11) Используется hydra  (https://hydra.cc/docs/intro/) (3 балла - доп баллы)

:heavy_minus_sign: 12) Настроен CI(прогон тестов, линтера) на основе github actions  (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome)

:heavy_plus_sign: 13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы)

2021-05-25 11:39 UTC, Sergey-Pravdyukov commented on ml_project/src/entities/pred_params.py
> +from .train_params import TrainingParams
Не используются импорты.

2021-05-25 11:42 UTC, Sergey-Pravdyukov commented on ml_project/tests/features/test_build_features.py
> +)
Это же нечитаемо. :)

2021-05-25 11:45 UTC, Sergey-Pravdyukov commented on ml_project/tests/features/test_rank_transformer.py
> +)
Выглядит не очень понятно и приятно, а также параметризация дублируется в следующей функции. Подумай в сторону DataClass, marchmallow, config.

2021-05-25 11:47 UTC, Sergey-Pravdyukov commented on ml_project/tests/models/test_models.py
> +    ],
Тут такой же совет про конфиги.

2021-05-25 11:47 UTC, Sergey-Pravdyukov commented on ml_project/tests/conftest.py
> +PROBA = 0.05
Тоже лечится конфигом.

2021-05-25 11:48 UTC, Sergey-Pravdyukov commented on ml_project/tests/conftest.py
> +@pytest.fixture
Почитай про scope фикстур. Например, на хабре есть замечательная [статья](https://habr.com/ru/post/448786/).

2021-05-25 11:50 UTC, Sergey-Pravdyukov commented on ml_project/tests/conftest.py
> +    return ["sex"]
Непрозрачная логика. Почему `categorical_features` это именно `["sex"]`?

2021-05-25 12:15 UTC, Sergey-Pravdyukov commented on ml_project/tests/conftest.py
> +            ],
Попробуй произвести рефакторинг этой части кода. Сейчас выглядит слишком громоздко, конструкции повторяются. 

Подсказка: избавиться от громоздкости до конца не получится, но попробуй улучшить  :)

2021-05-25 12:46 UTC, Sergey-Pravdyukov commented
Логгерами покрыт только пайплайн - верхушка айсберга. Попробуй покрыть логгированием также и каждый этап пайплайна внутри.

2021-05-25 12:52 UTC, Sergey-Pravdyukov commented
`python src/predict_pipeline.py artifacts_dir=outputs/train_1.0_2021-05-25_15-49-03 ` не могу запустить из корня. 

Получаю `FileNotFoundError: [Errno 2] No such file or directory: '../../data/raw/heart.csv'`. Поправь пожалуйста.

2021-05-25 12:54 UTC, Sergey-Pravdyukov commented
Также было бы здорово чтобы артефакты тренировки не были привязаны в директории зависящей от времени. Каждый раз конфигуровать `predict_pipeline` заново утомит кого угодно.

2021-05-25 12:56 UTC, Sergey-Pravdyukov commented
`PYTHONPATH=./src/ python -m pytest tests/ ` выглядит как велосипед с костылями.

2021-05-25 12:59 UTC, Sergey-Pravdyukov commented
Конфиги хорошо разбиты логически.

2021-05-25 13:41 UTC, Sergey-Pravdyukov requested changes
Готов усовершенствовать свое решение?

2021-05-25 13:41 UTC, Sergey-Pravdyukov commented on ml_project/tests/test_end_to_end.py
> +    ],
Ну и здесь тоже дублируется одна и та же параметризация.

2021-05-26 06:51 UTC, ningeen commented
да, вечером поправлю

2021-05-26 18:10 UTC, ningeen commented on ml_project/tests/features/test_build_features.py
> +)
Black так отформатировал)

2021-05-27 07:32 UTC, ningeen commented on ml_project/src/entities/pred_params.py
> +from .train_params import TrainingParams
убрал

2021-05-27 07:32 UTC, ningeen commented on ml_project/tests/features/test_build_features.py
> +)
исправил

2021-05-27 07:36 UTC, ningeen commented
> `PYTHONPATH=./src/ python -m pytest tests/` выглядит как велосипед с костылями.

исправил все, кроме этого. не знаю, как сделать по другому, у меня извечная проблема с этими относительными импортами в питоне. либо не работают импорты в тестах, либо в программе.

2021-05-27 07:38 UTC, ningeen commented
Кстати, во время праквки тестов появился вопрос: если у меня конфиг для тестов в фикстуре, можно как-то передать его в @pytest.mark.parametrize?

2021-05-31 19:29 UTC, Sergey-Pravdyukov approved these changes
Ок, ставлю 35 баллов.

2021-05-31 19:31 UTC, Sergey-Pravdyukov commented
> Кстати, во время правки тестов появился вопрос: если у меня конфиг для тестов в фикстуре, можно как-то передать его в @pytest.mark.parametrize?

Извини, боюсь не понял вопрос правильно. Поясни пожалуйста, если возможно приведи пример того как хочется чтобы выглядело.

2021-06-01 09:12 UTC, ningeen commented
> > Кстати, во время правки тестов появился вопрос: если у меня конфиг для тестов в фикстуре, можно как-то передать его в @pytest.mark.parametrize?
> 
> Извини, боюсь не понял вопрос правильно. Поясни пожалуйста, если возможно приведи пример того как хочется чтобы выглядело.

Вот есть у меня в test_build_features.py костыль: внутри функции test_make_features функция generate_cols_params. 
Изначально, она была отдельно и я хотел вызывать ее в `@pytest.mark.parametrize`, но для этого мне было необходимо передать туда конфиг (который сделан в виде фикстуры). 
Я хотел что-то типа такого:
```python
def generate_cols_params(config_test):
    ...
    return param

@pytest.mark.parametrize(  
    "param",   
    [generate_cols_params(config_test) for _ in range(10)]  
)  
def test_make_features(param):  
    ...  
```
Но в таком виде config_test не определен и использовать его нельзя. Вот я и думал, как лучше сделать. Загружать конфиг в переменную и в каждом тесте его импортить из conftest.py тоже не выглядит изящным решением.

2021-06-08 11:27 UTC, merged